src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 */
class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read=false;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="sent")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="received")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?Users
    {
        return $this->sender;
    }

    public function setSender(?Users $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?Users
    {
        return $this->recipient;
    }

    public function setRecipient(?Users $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Form/MessagesType.php
<?php

namespace App\Form;
use App\Entity\Users;
use App\Entity\Messages;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
class MessagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('title', TextType::class, [
            'label'=>"Objet",
            "attr" => [
                "class" => "form-control"
            ]
        ])
        ->add('message', TextareaType::class, [
            "attr" => [
                "class" => "form-control"
            ]
        ])
        ->add('recipient', EntityType::class, [
            "class" => Users::class,
            "choice_label" => "email",
            "attr" => [
                "class" => "form-control"
            ]
        ])
        ->add('created_at')
        ->add('is_read')
       
      
        ->add('envoyer', SubmitType::class, [
            "attr" => [
                "class" => "btn btn-primary"
            ]
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;
use App\Entity\Messages;
use App\Form\MessagesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class MessagesController extends AbstractController
{
    /**
     * @Route("/messages", name="messages")
     */
    public function index(): Response
    {
        return $this->render('messages/index.html.twig', [
            'controller_name' => 'MessagesController',
        ]);
    }
    /**
     * @Route("/send", name="send")
     */
    public function send(Request $request): Response
    {
        $message = new Messages;
        $form = $this->createForm(MessagesType::class, $message);
        
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $message->setSender($this->getUser());

            $em = $this->getDoctrine()->getManager();
            $em->persist($message);
            $em->flush();

            $this->addFlash("message", "Message envoyé avec succès.");
            return $this->redirectToRoute("messages");
        }

        return $this->render("messages/send.html.twig", [
            "form" => $form->createView()
        ]);
    }
/**
     * @Route("/received", name="received")
     */
    public function received(): Response
    {
        return $this->render('messages/received.html.twig');
    }
     /**
     * @Route("/sent", name="sent")
     */
    public function sent(): Response
    {
        return $this->render('messages/sent.html.twig');
    }

    /**
     * @Route("/read/{id}", name="read")
     */
    public function read(Messages $message): Response
    {
        $message->setIsRead(true);
        $em = $this->getDoctrine()->getManager();
        $em->persist($message);
        $em->flush();

        return $this->render('messages/read.html.twig', compact("message"));
    }

    /**
     * @Route("/delete/{id}", name="delete")
     */
    public function delete(Messages $message): Response
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($message);
        $em->flush();

        return $this->redirectToRoute("received");
    }

}

templates/messages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}

{% block body %}
<style>
.containt{
	display:flex;
	justify-content:space-around
}
 p{
	margin:20px
}
</style>

<div class="containt">

<div class="messagerie">

  <p> <a class="btn btn-primary" href="{{ path("messages") }}">Accueil</a></p>
  <p> <a class="btn btn-primary" href="{{ path("received") }}">Boîte de réception</a></p>
   <p><a  class="btn btn-primary" href="{{ path("sent") }}">Messages envoyés</a></p>
     <p><a  class="btn btn-primary" href="{{path("send")}}">Envoyés un message</a></p>

</div>

<div class="messagerie">

<p>Résumé de la messagerie</p>
<p>Reçus : {{ app.user.received|length }}</p>
<p>Envoyés : {{ app.user.sent|length }}</p>


</div>


</div>





{% endblock %}

templates/messages/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie
{% endblock %}

{% block body %}

<style>
.containt{
	display:flex;
	justify-content:space-around
}
 p{
	margin:20px
}
</style>

<div class="containt">

<div class="messagerie">

  <p> <a class="btn btn-primary" href="{{ path("messages") }}">Accueil</a></p>
  <p> <a class="btn btn-primary" href="{{ path("received") }}">Boîte de réception</a></p>
  <p><a  class="btn btn-primary" href="{{path("messages")}}">Envoyés un message</a></p>

</div>

<div class="messagerie">

	<h1>Messagerie</h1>
                <h2>{{ message.title }}</h2>
                <p>Message de {{ message.sender.email }}</p>
                <p>Le {{ message.createdAt|date }}</p>
                <div>{{ message.message }}</div>
				   <a href="{{path("received")}}" class="btn btn-primary">Retour à la boite de réception</a>

</div>


</div>







{% endblock %}

templates/messages/received.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie
{% endblock %}

{% block body %}
	<section class="container">
		<div class="row">
			<div class="col-12">
				<h1>Messagerie</h1>
				<h2>Boîte de réception</h2>
				<p>Vous avez reçu
					{{ app.user.received|length }}
					messages</p>
			</div>
			<div class="col-3">De</div>
			<div class="col-3">Sujet</div>
			<div class="col-3">Date</div>
			<div class="col-3">Actions</div>
			{% for message in app.user.received %}
				{% set bold = "" %}
				{% if message.isRead == 0 %}
					{% set bold = "fw-bold" %}
				{% endif %}

				<div class="col-3 {{bold}}">{{ message.sender.email }}</div>
				<div class="col-3 {{bold}}">
					<a href="{{ path("read", {id: message.id}) }}">{{ message.title }}</a>
				</div>
				<div class="col-3 {{bold}}">{{ message.createdAt|date }}</div>
				<div class="col-3">
                    <a href="{{ path("delete", {id: message.id}) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-excel-fill text-danger" viewbox="0 0 16 16">
                            <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM5.884 4.68L8 7.219l2.116-2.54a.5.5 0 1 1 .768.641L8.651 8l2.233 2.68a.5.5 0 0 1-.768.64L8 8.781l-2.116 2.54a.5.5 0 0 1-.768-.641L7.349 8 5.116 5.32a.5.5 0 1 1 .768-.64z"/>
                        </svg>
                    </a>
				</div>
			{% endfor %}


			<div class="col">
				<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Voir mes dossiers
				</a>
				<a href="{{path("send")}}" class="btn btn-primary">Envoyer un message</a>
			</div>
		</div>
	</section>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Accueil</a>
			</div>
			<div class="list-group">
				<a href="{{ path("received") }}" class="list-group-item list-group-item-action active">Boîte de réception</a>
			</div>
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Eléments envoyés</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/messages/send.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie
{% endblock %}

{% block body %}
	<section class="container">
		<div class="row">
			<div class="col">
				<h1>Envoyer un message</h1>
                {{ form(form) }}
				<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Voir mes dossiers
				</a>
			</div>
		</div>
	</section>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
            <div class="list-group">
                <a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Accueil</a>
            </div>
            <div class="list-group">
                <a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Boîte de réception</a>
            </div>
            <div class="list-group">
                <a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Eléments envoyés</a>
            </div>
		</div>
	</div>
{% endblock %}

templates/messages/sent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie
{% endblock %}

{% block body %}
	<section class="container">
		<div class="row">
			<div class="col-12">
				<h1>Messagerie</h1>
				<h2>Eléments envoyés</h2>
				<p>Vous avez envoyé
					{{ app.user.sent|length }}
					messages</p>
			</div>
			<div class="col-3">De</div>
			<div class="col-3">Sujet</div>
			<div class="col-3">Date</div>
			<div class="col-3">Actions</div>
			{% for message in app.user.sent %}
				{% set bold = "" %}
				{% if message.isRead == 0 %}
					{% set bold = "fw-bold" %}
				{% endif %}

				<div class="col-3 {{bold}}">{{ message.sender.email }}</div>
				<div class="col-3 {{bold}}">
					<a href="{{ path("read", {id: message.id}) }}">{{ message.title }}</a>
				</div>
				<div class="col-3 {{bold}}">{{ message.createdAt|date }}</div>
				<div class="col-3">
                    <a href="{{ path("delete", {id: message.id}) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-excel-fill text-danger" viewbox="0 0 16 16">
                            <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM5.884 4.68L8 7.219l2.116-2.54a.5.5 0 1 1 .768.641L8.651 8l2.233 2.68a.5.5 0 0 1-.768.64L8 8.781l-2.116 2.54a.5.5 0 0 1-.768-.641L7.349 8 5.116 5.32a.5.5 0 1 1 .768-.64z"/>
                        </svg>
                    </a>
				</div>
			{% endfor %}


			<div class="col">
				<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Voir mes dossiers
				</a>
				<a href="{{path("send")}}" class="btn btn-primary">Envoyer un message</a>
			</div>
		</div>
	</section>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Accueil</a>
			</div>
			<div class="list-group">
				<a href="{{ path("received") }}" class="list-group-item list-group-item-action">Boîte de réception</a>
			</div>
			<div class="list-group">
				<a href="{{ path("sent") }}" class="list-group-item list-group-item-action active">Eléments envoyés</a>
			</div>
		</div>
	</div>
{% endblock %}